### ISSUE TITLE
multiple classes

### ISSUE THREAD

**Issue by CinKKKyo** [minimaxir/imgbeddings#4]
Excuse me, I'm trying to use the work to clustering 4-classes datasets, while I following the instructions in "cat_dogs.ipynb", when using: umap.plot.points, raise a ValueError: "Plotting is currently only implemented for 2D embeddings", I pretty sure I follow the data structure as the repo given. Does it mean it just support binary classes? Thanks a lot~

**Comment by CinKKKyo** [comment]
When I change it to binary classes, it works well hhhhhhh

**Comment by minimaxir** [comment]
That depends on how you set up the classes with scikit-learn (the cat-dog example takes advantage of the fact that the classes are already encoded), but either way that's out of scope of the package itself.

The [plotting UMAP guide](https://umap-learn.readthedocs.io/en/latest/plotting.html) might be helpful.

**Comment by CinKKKyo** [comment]
Got it! I am going to following the tutorial you shared! Have a nice day!
